<?php namespace Anomaly\Streams\Platform\Model\Users;

use Anomaly\Streams\Platform\Entry\EntryModel;

class UsersUsersEntryModel extends EntryModel
{

    use \Illuminate\Database\Eloquent\SoftDeletes;

    protected $searchable = true;

    protected $versionable = false;

    protected $table = 'users_users';

    protected $titleName = 'display_name';

    protected $rules = [
        'email' => 'required|unique:users_users,email',
        'username' => 'required|unique:users_users,username',
        'password' => 'required',
        'roles' => 'required',
        'display_name' => 'required',
        'first_name' => '',
        'last_name' => '',
        'activated' => '',
        'enabled' => '',
        'permissions' => '',
        'last_login_at' => '',
        'remember_token' => '',
        'activation_code' => '',
        'reset_code' => '',
        'last_activity_at' => '',
        'ip_address' => '',
];

    protected $fields = [
        'email',
        'username',
        'password',
        'roles',
        'display_name',
        'first_name',
        'last_name',
        'activated',
        'enabled',
        'permissions',
        'last_login_at',
        'remember_token',
        'activation_code',
        'reset_code',
        'last_activity_at',
        'ip_address',
];

    protected $with = [];

    protected $dates = ['created_at', 'updated_at', 'last_login_at', 'last_activity_at', 'deleted_at'];

    protected $relationships = ['roles'];

    

    

    

    protected $stream = [
'id' => '21',
'sort_order' => '',
'namespace' => 'users',
'slug' => 'users',
'prefix' => 'users_',
'title_column' => 'display_name',
'order_by' => 'id',
'locked' => '0',
'hidden' => '0',
'sortable' => '0',
'searchable' => '1',
'trashable' => '1',
'translatable' => '0',
'versionable' => '0',
'config' => 'a:0:{}',
'assignments' => [
[
'id' => 127,
'sort_order' => 126,
'stream_id' => 21,
'field_id' => 106,
'config' => 'a:0:{}',
'unique' => 1,
'required' => 1,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '106',
'namespace' => 'users',
'slug' => 'email',
'type' => 'anomaly.field_type.email',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 106,
'field_id' => 106,
'locale' => 'en',
'name' => 'anomaly.module.users::field.email.name',
'placeholder' => 'anomaly.module.users::field.email.placeholder',
'warning' => 'anomaly.module.users::field.email.warning',
'instructions' => 'anomaly.module.users::field.email.instructions',
],
],
],
'translations' => [
[
'id' => 127,
'assignment_id' => 127,
'locale' => 'en',
'label' => 'anomaly.module.users::field.email.label.users',
'warning' => 'anomaly.module.users::field.email.warning.users',
'placeholder' => 'anomaly.module.users::field.email.placeholder.users',
'instructions' => 'anomaly.module.users::field.email.instructions.users',
],
],
],
[
'id' => 128,
'sort_order' => 127,
'stream_id' => 21,
'field_id' => 107,
'config' => 'a:0:{}',
'unique' => 1,
'required' => 1,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '107',
'namespace' => 'users',
'slug' => 'username',
'type' => 'anomaly.field_type.slug',
'config' => 'a:2:{s:4:"type";s:1:"_";s:9:"lowercase";b:0;}',
'locked' => '1',
'translations' => [
[
'id' => 107,
'field_id' => 107,
'locale' => 'en',
'name' => 'anomaly.module.users::field.username.name',
'placeholder' => 'anomaly.module.users::field.username.placeholder',
'warning' => 'anomaly.module.users::field.username.warning',
'instructions' => 'anomaly.module.users::field.username.instructions',
],
],
],
'translations' => [
[
'id' => 128,
'assignment_id' => 128,
'locale' => 'en',
'label' => 'anomaly.module.users::field.username.label.users',
'warning' => 'anomaly.module.users::field.username.warning.users',
'placeholder' => 'anomaly.module.users::field.username.placeholder.users',
'instructions' => 'anomaly.module.users::field.username.instructions.users',
],
],
],
[
'id' => 129,
'sort_order' => 128,
'stream_id' => 21,
'field_id' => 108,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '108',
'namespace' => 'users',
'slug' => 'password',
'type' => 'anomaly.field_type.text',
'config' => 'a:1:{s:4:"type";s:8:"password";}',
'locked' => '1',
'translations' => [
[
'id' => 108,
'field_id' => 108,
'locale' => 'en',
'name' => 'anomaly.module.users::field.password.name',
'placeholder' => 'anomaly.module.users::field.password.placeholder',
'warning' => 'anomaly.module.users::field.password.warning',
'instructions' => 'anomaly.module.users::field.password.instructions',
],
],
],
'translations' => [
[
'id' => 129,
'assignment_id' => 129,
'locale' => 'en',
'label' => 'anomaly.module.users::field.password.label.users',
'warning' => 'anomaly.module.users::field.password.warning.users',
'placeholder' => 'anomaly.module.users::field.password.placeholder.users',
'instructions' => 'anomaly.module.users::field.password.instructions.users',
],
],
],
[
'id' => 130,
'sort_order' => 129,
'stream_id' => 21,
'field_id' => 126,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '126',
'namespace' => 'users',
'slug' => 'roles',
'type' => 'anomaly.field_type.multiple',
'config' => 'a:1:{s:7:"related";s:34:"Anomaly\UsersModule\Role\RoleModel";}',
'locked' => '1',
'translations' => [
[
'id' => 126,
'field_id' => 126,
'locale' => 'en',
'name' => 'anomaly.module.users::field.roles.name',
'placeholder' => 'anomaly.module.users::field.roles.placeholder',
'warning' => 'anomaly.module.users::field.roles.warning',
'instructions' => 'anomaly.module.users::field.roles.instructions',
],
],
],
'translations' => [
[
'id' => 130,
'assignment_id' => 130,
'locale' => 'en',
'label' => 'anomaly.module.users::field.roles.label.users',
'warning' => 'anomaly.module.users::field.roles.warning.users',
'placeholder' => 'anomaly.module.users::field.roles.placeholder.users',
'instructions' => 'anomaly.module.users::field.roles.instructions.users',
],
],
],
[
'id' => 131,
'sort_order' => 130,
'stream_id' => 21,
'field_id' => 114,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '114',
'namespace' => 'users',
'slug' => 'display_name',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 114,
'field_id' => 114,
'locale' => 'en',
'name' => 'anomaly.module.users::field.display_name.name',
'placeholder' => 'anomaly.module.users::field.display_name.placeholder',
'warning' => 'anomaly.module.users::field.display_name.warning',
'instructions' => 'anomaly.module.users::field.display_name.instructions',
],
],
],
'translations' => [
[
'id' => 131,
'assignment_id' => 131,
'locale' => 'en',
'label' => 'anomaly.module.users::field.display_name.label.users',
'warning' => 'anomaly.module.users::field.display_name.warning.users',
'placeholder' => 'anomaly.module.users::field.display_name.placeholder.users',
'instructions' => 'anomaly.module.users::field.display_name.instructions.users',
],
],
],
[
'id' => 132,
'sort_order' => 131,
'stream_id' => 21,
'field_id' => 115,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '115',
'namespace' => 'users',
'slug' => 'first_name',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 115,
'field_id' => 115,
'locale' => 'en',
'name' => 'anomaly.module.users::field.first_name.name',
'placeholder' => 'anomaly.module.users::field.first_name.placeholder',
'warning' => 'anomaly.module.users::field.first_name.warning',
'instructions' => 'anomaly.module.users::field.first_name.instructions',
],
],
],
'translations' => [
[
'id' => 132,
'assignment_id' => 132,
'locale' => 'en',
'label' => 'anomaly.module.users::field.first_name.label.users',
'warning' => 'anomaly.module.users::field.first_name.warning.users',
'placeholder' => 'anomaly.module.users::field.first_name.placeholder.users',
'instructions' => 'anomaly.module.users::field.first_name.instructions.users',
],
],
],
[
'id' => 133,
'sort_order' => 132,
'stream_id' => 21,
'field_id' => 116,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '116',
'namespace' => 'users',
'slug' => 'last_name',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 116,
'field_id' => 116,
'locale' => 'en',
'name' => 'anomaly.module.users::field.last_name.name',
'placeholder' => 'anomaly.module.users::field.last_name.placeholder',
'warning' => 'anomaly.module.users::field.last_name.warning',
'instructions' => 'anomaly.module.users::field.last_name.instructions',
],
],
],
'translations' => [
[
'id' => 133,
'assignment_id' => 133,
'locale' => 'en',
'label' => 'anomaly.module.users::field.last_name.label.users',
'warning' => 'anomaly.module.users::field.last_name.warning.users',
'placeholder' => 'anomaly.module.users::field.last_name.placeholder.users',
'instructions' => 'anomaly.module.users::field.last_name.instructions.users',
],
],
],
[
'id' => 134,
'sort_order' => 133,
'stream_id' => 21,
'field_id' => 123,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '123',
'namespace' => 'users',
'slug' => 'activated',
'type' => 'anomaly.field_type.boolean',
'config' => 'a:1:{s:13:"default_value";b:0;}',
'locked' => '1',
'translations' => [
[
'id' => 123,
'field_id' => 123,
'locale' => 'en',
'name' => 'anomaly.module.users::field.activated.name',
'placeholder' => 'anomaly.module.users::field.activated.placeholder',
'warning' => 'anomaly.module.users::field.activated.warning',
'instructions' => 'anomaly.module.users::field.activated.instructions',
],
],
],
'translations' => [
[
'id' => 134,
'assignment_id' => 134,
'locale' => 'en',
'label' => 'anomaly.module.users::field.activated.label.users',
'warning' => 'anomaly.module.users::field.activated.warning.users',
'placeholder' => 'anomaly.module.users::field.activated.placeholder.users',
'instructions' => 'anomaly.module.users::field.activated.instructions.users',
],
],
],
[
'id' => 135,
'sort_order' => 134,
'stream_id' => 21,
'field_id' => 124,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '124',
'namespace' => 'users',
'slug' => 'enabled',
'type' => 'anomaly.field_type.boolean',
'config' => 'a:1:{s:13:"default_value";b:1;}',
'locked' => '1',
'translations' => [
[
'id' => 124,
'field_id' => 124,
'locale' => 'en',
'name' => 'anomaly.module.users::field.enabled.name',
'placeholder' => 'anomaly.module.users::field.enabled.placeholder',
'warning' => 'anomaly.module.users::field.enabled.warning',
'instructions' => 'anomaly.module.users::field.enabled.instructions',
],
],
],
'translations' => [
[
'id' => 135,
'assignment_id' => 135,
'locale' => 'en',
'label' => 'anomaly.module.users::field.enabled.label.users',
'warning' => 'anomaly.module.users::field.enabled.warning.users',
'placeholder' => 'anomaly.module.users::field.enabled.placeholder.users',
'instructions' => 'anomaly.module.users::field.enabled.instructions.users',
],
],
],
[
'id' => 136,
'sort_order' => 135,
'stream_id' => 21,
'field_id' => 113,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '113',
'namespace' => 'users',
'slug' => 'permissions',
'type' => 'anomaly.field_type.checkboxes',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 113,
'field_id' => 113,
'locale' => 'en',
'name' => 'anomaly.module.users::field.permissions.name',
'placeholder' => 'anomaly.module.users::field.permissions.placeholder',
'warning' => 'anomaly.module.users::field.permissions.warning',
'instructions' => 'anomaly.module.users::field.permissions.instructions',
],
],
],
'translations' => [
[
'id' => 136,
'assignment_id' => 136,
'locale' => 'en',
'label' => 'anomaly.module.users::field.permissions.label.users',
'warning' => 'anomaly.module.users::field.permissions.warning.users',
'placeholder' => 'anomaly.module.users::field.permissions.placeholder.users',
'instructions' => 'anomaly.module.users::field.permissions.instructions.users',
],
],
],
[
'id' => 137,
'sort_order' => 136,
'stream_id' => 21,
'field_id' => 111,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '111',
'namespace' => 'users',
'slug' => 'last_login_at',
'type' => 'anomaly.field_type.datetime',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 111,
'field_id' => 111,
'locale' => 'en',
'name' => 'anomaly.module.users::field.last_login_at.name',
'placeholder' => 'anomaly.module.users::field.last_login_at.placeholder',
'warning' => 'anomaly.module.users::field.last_login_at.warning',
'instructions' => 'anomaly.module.users::field.last_login_at.instructions',
],
],
],
'translations' => [
[
'id' => 137,
'assignment_id' => 137,
'locale' => 'en',
'label' => 'anomaly.module.users::field.last_login_at.label.users',
'warning' => 'anomaly.module.users::field.last_login_at.warning.users',
'placeholder' => 'anomaly.module.users::field.last_login_at.placeholder.users',
'instructions' => 'anomaly.module.users::field.last_login_at.instructions.users',
],
],
],
[
'id' => 138,
'sort_order' => 137,
'stream_id' => 21,
'field_id' => 109,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '109',
'namespace' => 'users',
'slug' => 'remember_token',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 109,
'field_id' => 109,
'locale' => 'en',
'name' => 'anomaly.module.users::field.remember_token.name',
'placeholder' => 'anomaly.module.users::field.remember_token.placeholder',
'warning' => 'anomaly.module.users::field.remember_token.warning',
'instructions' => 'anomaly.module.users::field.remember_token.instructions',
],
],
],
'translations' => [
[
'id' => 138,
'assignment_id' => 138,
'locale' => 'en',
'label' => 'anomaly.module.users::field.remember_token.label.users',
'warning' => 'anomaly.module.users::field.remember_token.warning.users',
'placeholder' => 'anomaly.module.users::field.remember_token.placeholder.users',
'instructions' => 'anomaly.module.users::field.remember_token.instructions.users',
],
],
],
[
'id' => 139,
'sort_order' => 138,
'stream_id' => 21,
'field_id' => 121,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '121',
'namespace' => 'users',
'slug' => 'activation_code',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 121,
'field_id' => 121,
'locale' => 'en',
'name' => 'anomaly.module.users::field.activation_code.name',
'placeholder' => 'anomaly.module.users::field.activation_code.placeholder',
'warning' => 'anomaly.module.users::field.activation_code.warning',
'instructions' => 'anomaly.module.users::field.activation_code.instructions',
],
],
],
'translations' => [
[
'id' => 139,
'assignment_id' => 139,
'locale' => 'en',
'label' => 'anomaly.module.users::field.activation_code.label.users',
'warning' => 'anomaly.module.users::field.activation_code.warning.users',
'placeholder' => 'anomaly.module.users::field.activation_code.placeholder.users',
'instructions' => 'anomaly.module.users::field.activation_code.instructions.users',
],
],
],
[
'id' => 140,
'sort_order' => 139,
'stream_id' => 21,
'field_id' => 119,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '119',
'namespace' => 'users',
'slug' => 'reset_code',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 119,
'field_id' => 119,
'locale' => 'en',
'name' => 'anomaly.module.users::field.reset_code.name',
'placeholder' => 'anomaly.module.users::field.reset_code.placeholder',
'warning' => 'anomaly.module.users::field.reset_code.warning',
'instructions' => 'anomaly.module.users::field.reset_code.instructions',
],
],
],
'translations' => [
[
'id' => 140,
'assignment_id' => 140,
'locale' => 'en',
'label' => 'anomaly.module.users::field.reset_code.label.users',
'warning' => 'anomaly.module.users::field.reset_code.warning.users',
'placeholder' => 'anomaly.module.users::field.reset_code.placeholder.users',
'instructions' => 'anomaly.module.users::field.reset_code.instructions.users',
],
],
],
[
'id' => 141,
'sort_order' => 140,
'stream_id' => 21,
'field_id' => 112,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '112',
'namespace' => 'users',
'slug' => 'last_activity_at',
'type' => 'anomaly.field_type.datetime',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 112,
'field_id' => 112,
'locale' => 'en',
'name' => 'anomaly.module.users::field.last_activity_at.name',
'placeholder' => 'anomaly.module.users::field.last_activity_at.placeholder',
'warning' => 'anomaly.module.users::field.last_activity_at.warning',
'instructions' => 'anomaly.module.users::field.last_activity_at.instructions',
],
],
],
'translations' => [
[
'id' => 141,
'assignment_id' => 141,
'locale' => 'en',
'label' => 'anomaly.module.users::field.last_activity_at.label.users',
'warning' => 'anomaly.module.users::field.last_activity_at.warning.users',
'placeholder' => 'anomaly.module.users::field.last_activity_at.placeholder.users',
'instructions' => 'anomaly.module.users::field.last_activity_at.instructions.users',
],
],
],
[
'id' => 142,
'sort_order' => 141,
'stream_id' => 21,
'field_id' => 110,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '110',
'namespace' => 'users',
'slug' => 'ip_address',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 110,
'field_id' => 110,
'locale' => 'en',
'name' => 'anomaly.module.users::field.ip_address.name',
'placeholder' => 'anomaly.module.users::field.ip_address.placeholder',
'warning' => 'anomaly.module.users::field.ip_address.warning',
'instructions' => 'anomaly.module.users::field.ip_address.instructions',
],
],
],
'translations' => [
[
'id' => 142,
'assignment_id' => 142,
'locale' => 'en',
'label' => 'anomaly.module.users::field.ip_address.label.users',
'warning' => 'anomaly.module.users::field.ip_address.warning.users',
'placeholder' => 'anomaly.module.users::field.ip_address.placeholder.users',
'instructions' => 'anomaly.module.users::field.ip_address.instructions.users',
],
],
],
],
'translations' => [
[
'id' => 21,
'stream_id' => 21,
'locale' => 'en',
'name' => 'anomaly.module.users::stream.users.name',
'description' => 'anomaly.module.users::stream.users.description',
],
],
];

    
    /**
     * The roles relation
     *
     * @return Relation
     */
    public function roles()
    {
        return $this->getFieldType('roles')->getRelation();
    }

}
